### ISSUE TITLE
Make UI more mobile-friendly

### ISSUE THREAD

**Issue by IdNotFound** [danielfireman/isumm#16]
Right now, the app on mobile has a very poor experience.

We should have some basic responsive design to make it more pleasant to track your investments on the go! :)

**Comment by danielfireman** [comment]
This great stuff! Two nits:
- The forms are broken when getting into 110% zoom (probably because of centralized elements, not sure though). See image attached
- Is there some way to get a max width for the charts?
  ![ui_broken_110](https://cloud.githubusercontent.com/assets/8951363/11091071/fb73f77e-8855-11e5-9fcc-870b55711887.png)
